### ISSUE TITLE
Siren Requests should be made with the header "Accept: application/vnd.siren+json"

### ISSUE THREAD

**Issue by tomdottom** [vertical-knowledge/pypermedia#7]
Currently the HypermediaClient will not work with any apis supporting both application/json and application/vnd.siren+json

Siren api requests should be made with the "Accept: application/vnd.siren+json" header.

A solution could be to add an option to set the type to the HypermediaClient constructor.
Alternatively SirenClient could be used when explicitly expecting to use application/vnd.siren+json.

A currently workaround is to ensure the request factory is always providing the correct headers.

```
from functools import partial
import requests

headered_req = partial(requests.Request, headers={'Accept': 'application/vnd.siren+json'})
client = HypermediaClient.connect('http://myapi.io/items/', request_factory=headered_req)
```

**Comment by timmartin19** [comment]
Fixed by #3
